### ISSUE TITLE
Request to change repository name to Tournament-Management-App and translate file names to English

### ISSUE THREAD

**Issue by AndresCdo** [AlexanderAsprilla98/Tournament-Management-App#11]
**Issue Description:**

Hello Alexander,

I hope you're doing well. I wanted to bring to your attention a couple of updates that I believe would improve the project's accessibility and clarity.

1. Change Repository Name:
Currently, the repository is named "TorneoFutbol," which is in Spanish. I suggest changing it to "Tournament-Management-App" to reflect the project's purpose in English, making it more inclusive for a global audience.

2. Translate File Names:
Additionally, I noticed that some of the file names are in Spanish. To enhance the project's readability and maintain a consistent language across the codebase, it would be beneficial to translate the file names from Spanish to English.

I'd be happy to contribute to these changes if you need any assistance.

Thank you for your consideration!

Best regards,
AndresCdo

**Comment by AlexanderAsprilla98** [comment]
@AndresCdo De acuerdo con la primera sugerencia, en cuanto al cambiar los nombre de archivos al ingles implecaria refactorizar muchas referencias internas en el  proyecto, se tendria que cambiar todo. Entonces se tomara como una sugerencia de mejora a futuro
